### ISSUE TITLE
Usage of this package

### ISSUE THREAD

**Issue by cricketthomas** [oleksis/setup-mpdev#1]
I am attempting to use this package, and it seems that we need to upload our own container containing Master Packager dev?
```
 - name: build MSIX with (Master Packager Dev)
      uses: oleksis/setup-mpdev@v1.2.0
      with:
        mpdev-params: "['build',  'mpdev/msix.json', '--verbose']"
```
![image](https://github.com/user-attachments/assets/64ee5e45-e0fc-44a8-b507-369393cc7afe)
